#!/bin/bash
# Boltz-2 cofolding: PMDsc structural homologs with 2x MVAP + ATP + Mg2+
# Generated by prepare_homolog_cofold.py

CONFIG_DIR=/nfs/lambda_stor_01/homes/rzhu/PMD/structures/homologs/cofold_configs
OUTPUT_DIR=/nfs/lambda_stor_01/homes/rzhu/PMD/structures/homologs/output_2mvap
LOG=$OUTPUT_DIR/run.log

mkdir -p $OUTPUT_DIR

echo "$(date): Starting homolog cofolding" | tee $LOG

GPU=${1:-0}  # Use GPU passed as argument, default 0
for YAML in $CONFIG_DIR/*.yaml; do
    NAME=$(basename $YAML .yaml)
    echo "$(date): Starting $NAME on GPU $GPU" | tee -a $LOG
    (
        CUDA_VISIBLE_DEVICES=$GPU conda run -n boltz-2 boltz predict \
            "$YAML" \
            --out_dir "$OUTPUT_DIR/$NAME" \
            --use_msa_server \
            --accelerator gpu \
            --recycling_steps 3 \
            --sampling_steps 200 \
            --diffusion_samples 50 \
            --output_format pdb \
            --no_kernels \
            > "$OUTPUT_DIR/${NAME}.log" 2>&1
        echo "$(date): $NAME done (exit code $?)" | tee -a $LOG
    )
done

echo "$(date): All homolog cofolding jobs finished." | tee -a $LOG
